### ISSUE TITLE
Graph with active cases

### ISSUE THREAD

**Issue by mgubis** [qsmd/covid19slovakia#2]
First of all, thanks for great work! It is awesome to see data normalized in both axis.

Just an idea: it would be quite interesting to see graph with active cases - it is significantly smaller set in South Korea now and we are slowly approaching the time, when there will be people recovering from the disease also in Slovakia.

**Comment by martinadamek** [comment]
Thanks for the idea. Not sure I will have the capacity to do it in coming weeks, but let's see.

**Comment by mgubis** [comment]
Thanks for feedback. I was thinking about trying to extend your import.py to generate also active cases data (although the data for Slovakia looks bit weird, it should be doable by combining time_series_covid19_confirmed_global.csv, time_series_covid19_deaths_global.csv and time_series_covid19_recovered_global.csv). I might have some questions here and there though.

So the question is, whether I can try to prepare PR (the code will be far from perfect - I am complete beginner in Python) or you prefer to keep it as the one-man show :)

**Comment by martinadamek** [comment]
The thing is, for SK and CZ I am not using data from CSSEGISandData, but updating manually from official SK/CZ sources.

I think this is the file you are looking for: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

I have that repository checked out locally and linked (and gitignored) time_series_covid19_confirmed_global.csv to that repo.

Don't worry about perfection, I am complete beginner in both Python and JavaScript ;-)

**Comment by mgubis** [comment]
Okay ... I will try to implement it (exact timeframe depends on my free time). I think, I will probably need to combine all three files (active cases = confirmed - deaths - recovered). Let's try to do it from CSSEGISandData (it integrates with current process nicely). You will probably need to link and ignore those other two files - I hope it is okay with you.

**Comment by mgubis** [comment]
Pull request #3 added. Please see description of the pull request itself for more information.

**Comment by martinadamek** [comment]
Merged to master from activecases branch.
